services:
  hmda-data-app:
    container_name: hmda-data-app
    image: dev-hmda-data-app
    depends_on:
      - redis
      - postgres
    volumes:
      - type: bind
        source: ./self-hosted-hmda-data-app
        target: /self-hosted-hmda-data-app
        read_only: true
    entrypoint: /self-hosted-hmda-data-app/dev_start_script.sh
  redis:
    container_name: redis-for-hmda-data-app
    image: redis
  postgres:
    container_name: postgres-for-hmda-data-app
    build:
      context: ./postgres-Docker-Image
      dockerfile: Dockerfile-postgres
    secrets:
      - postgres_password
  nginx:
    container_name: nginx-for-hmda-data-app
    image: nginx
    depends_on:
      - hmda-data-app
    volumes:
      - type: bind
        source: ./nginx-Docker-Image/nginx/conf.d
        target: /etc/nginx/conf.d
        read_only: true
    ports:
      - "8080:80"
secrets:
  postgres_password:
    file: ./postgres-DockerImage/secrets/postgres_password.txt