# syntax=docker/dockerfile:1

FROM python:3.8-buster
RUN apt-get -y update && apt-get -y install python3-dev libpq-dev
WORKDIR /self-hosted-hmda-data-app
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt